/**
 * Formatter
 * Converts raw agent results into GitHub PR comment bodies.
 */

const SEVERITY_EMOJI = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

const DIMENSION_EMOJI = {
  security: '🔐',
  performance: '⚡',
  logic: '🧠',
  style: '✨',
};

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];

/**
 * Build the main PR summary comment (posted once on the PR).
 */
function formatSummaryComment(prContext, agentResults) {
  const timestamp = new Date().toUTCString();
  const allIssues = collectAllIssues(agentResults);
  const counts = countBySeverity(allIssues);
  const overallScore = computeOverallScore(agentResults);
  const verdict = getVerdict(counts, overallScore);

  let md = `## 🤖 CodeReviewBot Analysis\n\n`;
  md += `> Analyzed PR: **${prContext.title}**  \n`;
  md += `> ${timestamp}\n\n`;

  // Overall verdict banner
  md += `### ${verdict.emoji} ${verdict.label}\n\n`;
  md += `${verdict.description}\n\n`;

  // Score table
  md += `### 📊 Scores by Dimension\n\n`;
  md += `| Dimension | Score | Issues Found |\n`;
  md += `|-----------|-------|--------------|\n`;

  for (const { agent, dimension, result, error } of agentResults) {
    const emoji = DIMENSION_EMOJI[dimension] || '🔍';
    const issueCount = result?.issues?.length ?? 0;
    const score = result?.score ?? 'N/A';
    const err = error ? ` *(error: ${error})*` : '';
    md += `| ${emoji} ${capitalize(dimension)} | ${score}/10 | ${issueCount} issue(s)${err} |\n`;
  }
  md += `| **Overall** | **${overallScore}/10** | **${allIssues.length} total** |\n\n`;

  // Issue summary by severity
  if (allIssues.length > 0) {
    md += `### 🗂 Issues Summary\n\n`;
    md += `| Severity | Count |\n|----------|-------|\n`;
    for (const sev of SEVERITY_ORDER) {
      if (counts[sev] > 0) {
        md += `| ${SEVERITY_EMOJI[sev]} ${capitalize(sev)} | ${counts[sev]} |\n`;
      }
    }
    md += '\n';

    // Critical and high issues listed inline
    const urgent = allIssues.filter((i) => ['critical', 'high'].includes(i.severity));
    if (urgent.length > 0) {
      md += `### 🚨 Critical & High Priority Issues\n\n`;
      for (const issue of urgent) {
        md += formatIssueSummary(issue);
      }
    }
  } else {
    md += `### ✅ No Issues Found\n\nThis PR looks clean across all review dimensions.\n\n`;
  }

  // Per-dimension summaries
  md += `### 📝 Dimension Summaries\n\n`;
  for (const { dimension, result } of agentResults) {
    const emoji = DIMENSION_EMOJI[dimension] || '🔍';
    md += `**${emoji} ${capitalize(dimension)}:** ${result?.summary || '_No summary available_'}\n\n`;
  }

  md += `---\n`;
  md += `<sub>Generated by [CodeReviewBot](https://github.com/your-org/codereviewbot) using Gemini 1.5 Flash • `;
  md += `[View docs](https://github.com/your-org/codereviewbot#readme)</sub>`;

  return md;
}

/**
 * Build inline review comments for specific lines in the diff.
 * Returns array of { path, line, body } objects for the GitHub API.
 */
function formatInlineComments(agentResults) {
  const allIssues = collectAllIssues(agentResults);
  const comments = [];

  for (const issue of allIssues) {
    // Only post inline comments for issues with a specific file+line
    if (!issue.file || !issue.line) continue;

    const emoji = SEVERITY_EMOJI[issue.severity] || '⚪';
    const dimEmoji = DIMENSION_EMOJI[issue.dimension] || '🔍';

    let body = `${emoji} **[${capitalize(issue.severity)}]** ${dimEmoji} ${issue.title}\n\n`;
    body += `${issue.description}\n\n`;

    if (issue.suggestion) {
      body += `**💡 Suggestion:** ${issue.suggestion}\n`;
    }

    if (issue.codeSnippet) {
      body += `\n\`\`\`\n${issue.codeSnippet}\n\`\`\`\n`;
    }

    comments.push({
      path: issue.file,
      line: issue.line,
      body,
      severity: issue.severity,
    });
  }

  // Sort: critical first
  comments.sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );

  return comments;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function collectAllIssues(agentResults) {
  const issues = [];
  for (const { dimension, result } of agentResults) {
    if (!result?.issues) continue;
    for (const issue of result.issues) {
      issues.push({ ...issue, dimension });
    }
  }
  return issues;
}

function countBySeverity(issues) {
  const counts = {};
  for (const sev of SEVERITY_ORDER) counts[sev] = 0;
  for (const issue of issues) {
    if (counts[issue.severity] !== undefined) counts[issue.severity]++;
  }
  return counts;
}

function computeOverallScore(agentResults) {
  const scores = agentResults.map((r) => r.result?.score).filter((s) => typeof s === 'number');
  if (scores.length === 0) return 'N/A';
  return (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(1);
}

function getVerdict(counts, score) {
  if (counts.critical > 0) {
    return { emoji: '🚫', label: 'Changes Required — Critical Issues Found', description: `This PR has **${counts.critical} critical issue(s)** that must be resolved before merging.` };
  }
  if (counts.high > 2) {
    return { emoji: '⚠️', label: 'Changes Requested', description: `Multiple high-severity issues need attention before this can be merged safely.` };
  }
  if (counts.high > 0 || counts.medium > 3) {
    return { emoji: '🔶', label: 'Needs Minor Fixes', description: `Some issues to address, but overall this PR is in reasonable shape.` };
  }
  return { emoji: '✅', label: 'Looks Good to Merge', description: `No critical or blocking issues found. Nice work!` };
}

function formatIssueSummary(issue) {
  const emoji = SEVERITY_EMOJI[issue.severity] || '⚪';
  const dimEmoji = DIMENSION_EMOJI[issue.dimension] || '🔍';
  let md = `- ${emoji} ${dimEmoji} **${issue.title}**`;
  if (issue.file) md += ` — \`${issue.file}\`${issue.line ? `:${issue.line}` : ''}`;
  md += `\n  ${issue.description}\n`;
  return md;
}

function capitalize(str) {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : '';
}

module.exports = { formatSummaryComment, formatInlineComments };
