/**
 * GitHub API Client
 * Posts summary comments and inline review comments to a PR.
 */

const https = require('https');

const GITHUB_API = 'api.github.com';

class GitHubClient {
  constructor(token) {
    if (!token) throw new Error('GITHUB_TOKEN is required');
    this.token = token;
  }

  /**
   * Post a general comment on a PR (used for the summary).
   */
  async postComment(owner, repo, prNumber, body) {
    const path = `/repos/${owner}/${repo}/issues/${prNumber}/comments`;
    return this._request('POST', path, { body });
  }

  /**
   * Post a review with inline comments.
   * @param {string} commitSha - The head commit SHA of the PR
   * @param {Array} comments - [{ path, line, body }]
   */
  async postReview(owner, repo, prNumber, commitSha, comments, event = 'COMMENT') {
    const path = `/repos/${owner}/${repo}/pulls/${prNumber}/reviews`;

    // GitHub requires line numbers relative to the diff, not the file.
    // We post as COMMENT (no approval/rejection) to stay neutral.
    const payload = {
      commit_id: commitSha,
      body: '', // summary is posted separately
      event,
      comments: comments.map((c) => ({
        path: c.path,
        line: c.line,
        body: c.body,
        side: 'RIGHT',
      })),
    };

    return this._request('POST', path, payload);
  }

  /**
   * Get PR details including head commit SHA and file list.
   */
  async getPR(owner, repo, prNumber) {
    const path = `/repos/${owner}/${repo}/pulls/${prNumber}`;
    return this._request('GET', path);
  }

  /**
   * Get the unified diff for a PR.
   */
  async getPRDiff(owner, repo, prNumber) {
    const path = `/repos/${owner}/${repo}/pulls/${prNumber}`;
    return this._request('GET', path, null, 'application/vnd.github.diff');
  }

  /**
   * List files changed in a PR.
   */
  async getPRFiles(owner, repo, prNumber) {
    const path = `/repos/${owner}/${repo}/pulls/${prNumber}/files`;
    return this._request('GET', path);
  }

  /**
   * Delete bot's previous review comments (to avoid spam on re-runs).
   */
  async deletePreviousBotComments(owner, repo, prNumber) {
    const path = `/repos/${owner}/${repo}/issues/${prNumber}/comments`;
    const comments = await this._request('GET', path);

    const botComments = comments.filter(
      (c) => c.body?.includes('🤖 CodeReviewBot Analysis') || c.body?.includes('Generated by [CodeReviewBot]')
    );

    for (const comment of botComments) {
      await this._request('DELETE', `/repos/${owner}/${repo}/issues/comments/${comment.id}`);
      console.log(`🗑  Deleted old comment ${comment.id}`);
    }
  }

  _request(method, path, body = null, accept = 'application/vnd.github+json') {
    return new Promise((resolve, reject) => {
      const options = {
        hostname: GITHUB_API,
        path,
        method,
        headers: {
          Authorization: `Bearer ${this.token}`,
          Accept: accept,
          'User-Agent': 'CodeReviewBot/1.0',
          'X-GitHub-Api-Version': '2022-11-28',
          ...(body ? { 'Content-Type': 'application/json' } : {}),
        },
      };

      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (chunk) => (data += chunk));
        res.on('end', () => {
          if (res.statusCode === 204) return resolve(null); // DELETE success
          if (res.statusCode >= 400) {
            return reject(new Error(`GitHub API ${res.statusCode}: ${data}`));
          }
          try {
            resolve(JSON.parse(data));
          } catch {
            resolve(data); // diff endpoint returns plain text
          }
        });
      });

      req.on('error', reject);
      if (body) req.write(JSON.stringify(body));
      req.end();
    });
  }
}

module.exports = { GitHubClient };
